name:                slick-site-builder
version:             0.1.0.0
github:              "cordx56/slick-site-builder"
license:             BSD3
author:              "cordx56"
maintainer:          "cordx56@cordx.cx"
copyright:           "2023 cordx56"

extra-source-files:
- README.md

synopsis:            My site builder using Slick.
category:            Slick-Site

description: Slick site builder

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - time
    - pandoc
    - yaml
